name: Setup Minikube (Task 2)

on:
  workflow_dispatch:
    inputs:
      target_ip:
        description: 'IP сервера chuikova-node'
        required: true
        type: string

jobs:
  ansible-check:
    name: Dry Run Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ github.event.inputs.target_ip }} >> ~/.ssh/known_hosts

      - name: Run Ansible Dry Run
        run: |
          cd task2
          ansible-playbook -i "${{ github.event.inputs.target_ip }}," playbook.yml --check

  ansible-deploy:
    name: Install Components
    needs: ansible-check 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ github.event.inputs.target_ip }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          cd task2
          ansible-playbook -i "${{ github.event.inputs.target_ip }}," playbook.yml
